<?php

/**
 * @file
 * Module used to house customizations for Simon Fraser University.
 */

define('ISLANDORA_PYDIO_BRIDGE_INGEST_PATH', 'islandora_pydio_bridge/ingest');
define('ISLANDORA_PYDIO_BRIDGE_XACML_FOLDER', '/xacml');
define('ISLANDORA_PYDIO_BRIDGE_PYDIO_URI', 'http://pyd.io#');
define('ISLANDORA_PYDIO_BRIDGE_PYDIO_FRAME', 'pydio_bridge/pydio');

/**
 * Implements hook_menu().
 */
function islandora_pydio_bridge_menu() {
  $items = array();

  $items[ISLANDORA_PYDIO_BRIDGE_INGEST_PATH] = array(
    'title' => 'Ingest',
    'access callback' => 'islandora_pydio_bridge_access_callback',
    'page callback' => 'islandora_pydio_bridge_ingest',
    'file' => 'includes/pydio_ingest.inc',
    'type' => MENU_CALLBACK,
  );
  $items[ISLANDORA_PYDIO_BRIDGE_PYDIO_FRAME] = array(
    'title' => 'Islandora Pydio Bridge',
    'access callback' => 'islandora_pydio_bridge_access_callback',
    'page callback' => 'drupal_goto',
    'page arguments' => array(variable_get("islandora_pydio_bridge_pydio_path", 'pydio')),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/islandora/islandora_pydio_bridge'] = array(
    'title' => 'Islandora Pydio Bridge Settings',
    'description' => 'Configure settings for the Islandora Pydio Bridge module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_pydio_bridge_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );

  return $items;
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pydio_bridge_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_pydio_bridge');
  // SFU Generic Content Model. in a ipb (islandora pydio bridge namespace).
  $generic_cmodel = $connection->repository->constructObject('ipb:genericCModel');
  $generic_cmodel->owner = 'fedoraAdmin';
  $generic_cmodel->label = 'Islandora Miscellaneous File Format Content Model';
  $generic_cmodel->models = 'fedora-system:ContentModel-3.0';
  $datastream = $generic_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/data/datastreams/generic_CModel/DS-COMPOSITE-MODEL.xml", FALSE);
  $generic_cmodel->ingestDatastream($datastream);

  return array(
    'islandora_pydio_bridge' => array(
      'title' => 'Islandora Pydio Bridge',
      'objects' => array(
        $generic_cmodel,
      ),
    ),
  );
}

/**
 * Menu access callback.
 */
function islandora_pydio_bridge_access_callback() {
  global $user;

  $object = islandora_object_load(variable_get('islandora_pydio_bridge_repository_pid', 'islandora:root'));
  return in_array('authenticated user', $user->roles) && islandora_object_access(ISLANDORA_INGEST, $object, $user);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_pydio_bridge_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_pydio_bridge');
  return array(
    'Islandora Pydio Bridge DDI form' => array(
      'form_file' => "$module_path/xml/DDI_final.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_pydio_bridge_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_pydio_bridge_generic_form' => array(
      'content_model' => 'islandora:binaryObjectCModel',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_basic_image_form' => array(
      'content_model' => 'islandora:sp_basic_image',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_large_image_form' => array(
      'content_model' => 'islandora:sp_large_image_cmodel',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_pdf_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_video_form' => array(
      'content_model' => 'islandora:sp_videoCModel',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_audio_form' => array(
      'content_model' => 'islandora:sp-audioCModel',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
    'islandora_pydio_bridge_data_form' => array(
      'content_model' => 'islandora:sp_data',
      'form_name' => 'Islandora Pydio Bridge DDI form',
      'dsid' => 'DDI',
      'title_field' => array('stdyDscr', 'citation', 'titlStmt', 'titl'),
      'transform' => 'ddi_to_dc.xsl',
      'self_transform' => 'cleanup_ddi.xsl',
      'template' => FALSE,
    ),
  );
 }
 
 /**
  * Implements hook_islandora_xml_form_builder_get_transforms().
  */
function islandora_pydio_bridge_islandora_xml_form_builder_get_transforms() {
  $module_path = drupal_get_path('module', 'islandora_pydio_bridge');
  return array(
    'ddi_to_dc.xsl' => "$module_path/xml/ddi_to_dc.xsl",
  );
}

/**
 * Implements hook_xml_form_builder_get_self_transforms().
 */
function islandora_pydio_bridge_xml_form_builder_get_self_transforms() {
  $module_path = drupal_get_path('module', 'islandora_pydio_bridge');
  return array(
    'cleanup_ddi.xsl' => "$module_path/xml/cleanup_ddi.xsl",
  );
}
